import { configureStore } from '@acemarke/redux-starter-kit';
import reducer from '../ducks';

const state = '{"objects":{"animations":[{"id":"rJiN16HKm","_inspector":{"modelType":"animation","editableFields":[{"fieldKey":"name","displayName":"Name"},{"fieldKey":"delay","displayName":"Delay"},{"fieldKey":"repeat","displayName":"Repeat"}]},"name":"New Animation","delay":0,"repeat":false,"frames":["HkR4J6HFX","HygAVkpHKX","Sk-0EJaBF7","Skq816HFX"]},{"id":"B1hVkTHFm","_inspector":{"modelType":"animation","editableFields":[{"fieldKey":"name","displayName":"Name"},{"fieldKey":"delay","displayName":"Delay"},{"fieldKey":"repeat","displayName":"Repeat"}]},"name":"New Animation","delay":0,"repeat":false,"frames":[]},{"id":"BJlhVy6SFQ","_inspector":{"modelType":"animation","editableFields":[{"fieldKey":"name","displayName":"Name"},{"fieldKey":"delay","displayName":"Delay"},{"fieldKey":"repeat","displayName":"Repeat"}]},"name":"New Animation","delay":0,"repeat":false,"frames":[]}],"frames":[{"id":"HkR4J6HFX","_inspector":{"modelType":"frame","editableFields":[{"fieldKey":"sourceRect","displayName":"Rectangle"},{"fieldKey":"offset","displayName":"Offset"}]},"name":"New Frame","sourceRect":{"x":0,"y":64,"width":64,"height":64},"offset":{"x":0,"y":0},"colliders":[]},{"id":"HygAVkpHKX","_inspector":{"modelType":"frame","editableFields":[{"fieldKey":"sourceRect","displayName":"Rectangle"},{"fieldKey":"offset","displayName":"Offset"}]},"name":"New Frame","sourceRect":{"x":128,"y":64,"width":64,"height":64},"offset":{"x":0,"y":0},"colliders":[]},{"id":"Sk-0EJaBF7","_inspector":{"modelType":"frame","editableFields":[{"fieldKey":"sourceRect","displayName":"Rectangle"},{"fieldKey":"offset","displayName":"Offset"}]},"name":"New Frame","sourceRect":{"x":64,"y":64,"width":64,"height":64},"offset":{"x":0,"y":0},"colliders":[]},{"id":"Skq816HFX","_inspector":{"modelType":"frame","editableFields":[{"fieldKey":"sourceRect","displayName":"Rectangle"},{"fieldKey":"offset","displayName":"Offset"}]},"name":"New Frame","sourceRect":{"x":192,"y":64,"width":64,"height":64},"offset":{"x":0,"y":0},"colliders":[]}],"colliders":[]},"selection":{"selectedAnimationId":"rJiN16HKm","selectedItemId":"Skq816HFX","selectedFrameId":"Skq816HFX"},"ui":{"framesVisible":true,"collidersVisible":true}}';
const preloadedState = JSON.parse(state);

export default () => {
  return configureStore({ reducer, preloadedState });
};
